### PR TITLE
iterators use <=>,==

### PR DESCRIPTION
**Pull request by rscohn2**
Convert some iterators to use <=>, == to define all relational operations

### CODE REVIEW

**Comment by rscohn2** [comment]
Setting this aside for now. I have mhp working, but shp fails to compile.

**Comment by BenBrock** [comment]
I need to look into this.  The spaceship operator greatly simplifies some things.

**Comment by rscohn2** [comment]
I gave you write access to my fork in case you want to push updates to this branch.

I did make 2 attempts to enable SHP, but I ran into type issues that I did not understand

**Comment by rscohn2** [comment]
Closing. @BenBrock noted that we may want to support iterators that do not implement `<=>`

**Pull request closed without merging**
